spring:
  profiles.active: "local"
  messages:
    basename: messages/messages
    encoding: UTF-8
    jackson:
      dfault-property-inclusion: non_null
    application:
      name: storm-sns
    servlet:
      multipart:
        max-file-size: 30MB
        max-request-size: 30MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8443


---
spring:
  config.activeate.on-profile: jdbc
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.34.208.34:3306/STORM_SCORE
    name: root
    password: tmxha1925
    username: root
    sql-script-encoding: "UTF-8"

mybatis:
  type-aliases-package: com.storm.score.domain
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse

jwt:
  header: Authorization
  secret: zxspoieqwroaisefjoiju124509uasdfoikjaSEdf09u2049i-0asd0-f9uawsefaoiswjef0o414poiasdf09oasidef09ao9wjpo2j5poq3i5t-0q3ispaodfiaspoej51230945u109-284i-0iasd-0Fkasdf09juasfg092qma3ro0kawert0aiwer9amsve90awi3rt0q23i8509q24hyae098srgjas-0edfriaw309rtuawq309trjasefgtiawet0iawe0frkas09f9asdklfjasdofwoeifhasoidfmasoidfj1o35123582789571239084qwpeoirjawdfjklhasdfiuasdhfoiasjefoiawef982y345982137y498q23r89q2735982q37y598123h4rqwi9jefqw9487ty52q938ryqwp9038ru7q2398ryuw9eifrjwae98fu
  token-validity-in-seconds: 86400


